"use client";

import { useEffect, useState } from "react";
import { Archive, BarChart3, Bell, BookOpenCheck, Brain, CheckCircle2, ChevronRight, Flame, Gauge, Heart, History, Leaf, LogOut, Menu, Moon, Plus, Search, Settings, Sparkles, Sun, Target, TrendingDown, X } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { deadlineState } from "@/lib/penalty-engine";

type Mistake={id:number;name:string;category:string;color:string;count:number;trigger:string;intention:string};
type RecordItem={id:number;mistakeId:number;date:string;iso:string;note:string;feeling:string;lesson:string};
type Commitment={id:number;mistakeId:number;title:string;due:string;status:"pending"|"done";reason:string};

const defaults:Mistake[]=[
  {id:1,name:"Procrastinating",category:"Productivity",color:"#6d63d9",count:7,trigger:"Large or unclear tasks",intention:"I will start with just five minutes"},
  {id:2,name:"Too much phone time",category:"Focus",color:"#3676d8",count:5,trigger:"Tiredness or boredom",intention:"I will leave my phone outside the room"},
  {id:3,name:"Going to bed late",category:"Health",color:"#8055c8",count:4,trigger:"Watching videos at night",intention:"I will turn screens off at 10:30"},
  {id:4,name:"Reacting too quickly",category:"Relationships",color:"#dd5f69",count:3,trigger:"Feeling ignored",intention:"I will take three breaths before replying"},
  {id:5,name:"Unplanned spending",category:"Money",color:"#df9638",count:2,trigger:"Online sales",intention:"I will use the 24-hour waiting rule"},
  {id:6,name:"Skipping exercise",category:"Health",color:"#16967a",count:4,trigger:"Feeling short on time",intention:"I will do the 10-minute version"},
  {id:7,name:"Overcommitting",category:"Boundaries",color:"#c34f8c",count:2,trigger:"Finding it hard to say no",intention:"I will check my calendar first"},
  {id:8,name:"Harsh self-criticism",category:"Mindfulness",color:"#4b85a8",count:6,trigger:"Mistakes or comparison",intention:"I will speak to myself like a friend"},
];
const seedRecords:RecordItem[]=[
  {id:1,mistakeId:1,date:"Today, 10:20",iso:"2026-07-23",note:"I delayed the report until late morning.",feeling:"Anxious",lesson:"Break it into three small steps."},
  {id:2,mistakeId:2,date:"Yesterday, 22:40",iso:"2026-07-22",note:"I scrolled without purpose for an hour.",feeling:"Tired",lesson:"Keep my phone out of the bedroom."},
  {id:3,mistakeId:4,date:"2 days ago",iso:"2026-07-21",note:"I answered before listening fully.",feeling:"Upset",lesson:"Practice a three-breath pause."},
  {id:4,mistakeId:3,date:"3 days ago",iso:"2026-07-20",note:"I stayed awake until 1 a.m.",feeling:"Bored",lesson:"Set a screen-off reminder."},
];
const seedCommitments:Commitment[]=[
  {id:1,mistakeId:1,title:"25 minutes of distraction-free work",due:"2026-07-24",status:"pending",reason:"Reset after today's delay"},
  {id:2,mistakeId:2,title:"One night with the phone outside",due:"2026-07-23",status:"pending",reason:"Restore my focus"},
  {id:3,mistakeId:4,title:"Write one empathetic message",due:"2026-07-25",status:"pending",reason:"Repair the relationship"},
  {id:4,mistakeId:3,title:"Sleep before 11 p.m.",due:"2026-07-20",status:"done",reason:"Protect tomorrow's energy"},
];
const weekly=[{day:"Mon",count:3},{day:"Tue",count:2},{day:"Wed",count:4},{day:"Thu",count:2},{day:"Fri",count:1},{day:"Sat",count:2},{day:"Sun",count:1}];
const nav=[["dashboard","My Today",Gauge],["mistakes","My Patterns",Brain],["commitments","My Commitments",Target],["journal","Growth Journal",BookOpenCheck],["insights","Insights",BarChart3],["archive","History",History],["settings","Settings",Settings]] as const;

export function DisciplineApp(){
  const [authenticated,setAuthenticated]=useState(()=>typeof window!=="undefined"&&sessionStorage.getItem("growth-en-session")==="me");
  const [page,setPage]=useState("dashboard"),[dark,setDark]=useState(false),[query,setQuery]=useState(""),[error,setError]=useState("");
  const load=()=>{if(typeof window==="undefined")return null;try{return JSON.parse(localStorage.getItem("personal-growth-en")??"")}catch{return null}};
  const [records,setRecords]=useState<RecordItem[]>(()=>load()?.records??seedRecords);
  const [commitments,setCommitments]=useState<Commitment[]>(()=>load()?.commitments??seedCommitments);
  const [patterns,setPatterns]=useState<Mistake[]>(()=>load()?.patterns??defaults);
  const [modal,setModal]=useState<Mistake|null>(null),[custom,setCustom]=useState(false),[note,setNote]=useState(""),[feeling,setFeeling]=useState("Tired"),[lesson,setLesson]=useState(""),[toast,setToast]=useState("");
  useEffect(()=>localStorage.setItem("personal-growth-en",JSON.stringify({records,commitments,patterns})),[records,commitments,patterns]);
  useEffect(()=>{document.documentElement.classList.toggle("dark",dark)},[dark]);
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(""),2600);return()=>clearTimeout(id)},[toast]);
  const mistake=(id:number)=>patterns.find(m=>m.id===id)!;
  const pending=commitments.filter(c=>c.status==="pending");
  const filtered=patterns.filter(m=>(m.name+m.category+m.trigger).toLowerCase().includes(query.toLowerCase()));
  const title=nav.find(n=>n[0]===page)?.[1]??"My Today";
  const occurrence=(id:number)=>records.filter(r=>r.mistakeId===id).length+1;
  function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);if(d.get("email")==="me@example.com"&&d.get("password")==="MyJourney123!"){sessionStorage.setItem("growth-en-session","me");setAuthenticated(true);setError("")}else setError("The email or password is incorrect.")}
  function register(){if(!modal)return;const due=new Date();due.setDate(due.getDate()+1);setRecords(v=>[{id:Date.now(),mistakeId:modal.id,date:"Just now",iso:new Date().toISOString().slice(0,10),note,feeling,lesson},...v]);setCommitments(v=>[{id:Date.now()+1,mistakeId:modal.id,title:lesson||modal.intention,due:due.toISOString().slice(0,10),status:"pending",reason:`A small step after occurrence ${occurrence(modal.id)}`},...v]);setModal(null);setNote("");setLesson("");setToast("Saved without judgment — one small step forward.")}
  function createPattern(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),name=String(d.get("name")??"").trim();if(!name)return;setPatterns(v=>[{id:Date.now(),name,category:String(d.get("category")||"Personal"),color:"#6257d5",count:0,trigger:String(d.get("trigger")||"Not identified yet"),intention:String(d.get("intention")||"I will pause and choose deliberately next time")},...v]);setCustom(false);setToast("Your custom pattern is ready to track.")}
  function complete(id:number){setCommitments(v=>v.map(c=>c.id===id?{...c,status:"done"}:c));setToast("Well done! Your small win is in the journal.")}
  if(!authenticated)return <div className="login-page"><div className="login-card card"><div className="brand-mark" style={{margin:"0 auto 16px",color:"white",background:"#6257d5"}}><Leaf size={22}/></div><h1>My Path</h1><p className="muted">A private place to notice patterns and grow without judgment</p><form onSubmit={login}><label>Email<input className="field" name="email" type="email" defaultValue="me@example.com" required/></label><label>Password<input className="field" name="password" type="password" defaultValue="MyJourney123!" required/></label>{error&&<div className="login-error">{error}</div>}<button className="btn btn-primary"><Heart size={17}/> Enter my private space</button></form><div className="demo-hint">The personal demo account is pre-filled.</div></div></div>;
  return <div className="app-shell">
    <aside className="sidebar" style={{background:"#18233a"}}><div className="brand"><div className="brand-mark" style={{background:"#6257d5"}}><Leaf size={21}/></div><div><b>My Path</b><div style={{fontSize:10,opacity:.65}}>Personal growth journal</div></div></div><div className="nav">{nav.map(([id,label,Icon])=><button key={id} className={page===id?"active":""} onClick={()=>setPage(id)}><Icon size={18}/><span>{label}</span>{id==="commitments"&&<span className="badge purple" style={{marginLeft:"auto"}}>{pending.length}</span>}</button>)}</div><div className="gentle-note"><Sparkles size={16}/><span>The goal is not perfection. It is greater awareness and a better choice next time.</span></div><div style={{marginTop:"auto",borderTop:"1px solid #ffffff18",paddingTop:15}}><div className="person"><div className="avatar">M</div><div><b style={{fontSize:13}}>My private space</b><div style={{fontSize:10,opacity:.6}}>Private and secure</div></div></div><button className="btn" onClick={()=>{sessionStorage.removeItem("growth-en-session");setAuthenticated(false)}} style={{color:"#cbd8ef",background:"transparent",marginTop:10}}><LogOut size={16}/> Sign out</button></div></aside>
    <main className="main"><header className="header"><div style={{display:"flex",alignItems:"center",gap:10}}><button className="btn btn-soft mobile-menu"><Menu size={18}/></button><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a pattern or note..."/></div></div><div style={{display:"flex",gap:8}}><button className="btn btn-soft" onClick={()=>setDark(v=>!v)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="btn btn-soft"><Bell size={18}/></button></div></header>
      <div className="content"><div className="topline"><div><h1>{title}</h1><div className="muted">Thursday, July 23 · Today is a fresh opportunity</div></div><button className="btn btn-primary" onClick={()=>setPage("mistakes")}><Plus size={17}/> Log an event</button></div>
        {page==="dashboard"&&<Dashboard records={records} commitments={commitments} mistake={mistake} go={setPage}/>}
        {page==="mistakes"&&<Patterns items={filtered} records={records} open={setModal} home={()=>setPage("dashboard")} create={()=>setCustom(true)}/>}
        {page==="commitments"&&<Commitments items={pending} mistake={mistake} complete={complete}/>}
        {page==="journal"&&<Journal records={records} commitments={commitments} mistake={mistake}/>}
        {page==="insights"&&<Insights records={records} patterns={patterns}/>}
        {page==="archive"&&<HistoryView records={records} mistake={mistake}/>}
        {page==="settings"&&<SettingsView/>}
      </div></main>
    {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="section-title"><div><h2>Notice with kindness, not blame</h2><div className="muted">This private note helps you understand the pattern.</div></div><button className="btn btn-soft" onClick={()=>setModal(null)}><X size={17}/></button></div><div className="reflection-card"><Brain size={20}/><div><b>{modal.name}</b><div className="muted">Approximately occurrence {occurrence(modal.id)} · Common trigger: {modal.trigger}</div></div></div><div className="form-grid"><label className="full">What happened?<textarea className="field" rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Write briefly and honestly..."/></label><label>How did I feel?<select className="field" value={feeling} onChange={e=>setFeeling(e.target.value)}><option>Tired</option><option>Anxious</option><option>Angry</option><option>Bored</option><option>Afraid</option><option>Pressured</option></select></label><label>My next small step<input className="field" value={lesson} onChange={e=>setLesson(e.target.value)} placeholder={modal.intention}/></label></div><div style={{display:"flex",justifyContent:"flex-end",gap:9}}><button className="btn btn-soft" onClick={()=>setModal(null)}>Not now</button><button className="btn btn-primary" onClick={register}><Sparkles size={17}/> Save and create commitment</button></div></div></div>}
    {custom&&<div className="modal-backdrop" onMouseDown={()=>setCustom(false)}><form className="modal" onSubmit={createPattern} onMouseDown={e=>e.stopPropagation()}><div className="section-title"><div><h2>Create a custom pattern</h2><div className="muted">Write anything you want to track personally.</div></div><button type="button" className="btn btn-soft" onClick={()=>setCustom(false)}><X size={17}/></button></div><div className="form-grid"><label>Pattern name<input className="field" name="name" required placeholder="e.g. Interrupting others"/></label><label>Category<input className="field" name="category" placeholder="e.g. Relationships"/></label><label className="full">Possible trigger<input className="field" name="trigger" placeholder="When does it usually happen?"/></label><label className="full">My next-time intention<input className="field" name="intention" placeholder="e.g. I will pause for three seconds"/></label></div><div style={{display:"flex",justifyContent:"flex-end",gap:9}}><button type="button" className="btn btn-soft" onClick={()=>setCustom(false)}>Cancel</button><button className="btn btn-primary"><Plus size={17}/> Create pattern</button></div></form></div>}
    {toast&&<div className="toast"><CheckCircle2 size={17} style={{display:"inline",marginRight:8}}/>{toast}</div>}
  </div>;
}

function Dashboard({records,commitments,mistake,go}:{records:RecordItem[];commitments:Commitment[];mistake:(id:number)=>Mistake;go:(p:string)=>void}){const pending=commitments.filter(c=>c.status==="pending"),done=commitments.filter(c=>c.status==="done");const stats=[["Entries this month",records.length+9,Brain,"#eeecff","#6257d5","More awareness"],["Mindful days","12",Flame,"#fff1e4","#d47819","4-day streak"],["Open commitments",pending.length,Target,"#e9f0ff","#3768d9","My next small steps"],["Completed commitments",done.length+8,CheckCircle2,"#e7f7ef","#188663","82% completion rate"]] as const;return <><div className="welcome-card card"><div><span className="badge purple">Today&apos;s reflection</span><h2>Be kind to yourself. Change begins with noticing.</h2><p>Observe one pattern today and choose one clear, manageable step.</p></div><div className="welcome-orb"><Leaf size={34}/></div></div><div className="stats">{stats.map(([label,value,Icon,bg,color,note])=><div className="card stat" key={label}><div className="stat-head"><span className="muted">{label}</span><div className="icon-box" style={{background:bg,color}}><Icon size={19}/></div></div><strong>{value}</strong><span className="positive">{note}</span></div>)}</div><div className="grid-2"><section className="card section"><div className="section-title"><div><h2>Weekly pattern trend</h2><div className="muted">Aim for gentle, sustainable change</div></div><span className="badge green"><TrendingDown size={12}/> 18% lower</span></div><div className="chart"><ResponsiveContainer><AreaChart data={weekly}><CartesianGrid stroke="var(--line)" vertical={false}/><XAxis dataKey="day" axisLine={false}/><YAxis axisLine={false}/><Tooltip/><Area type="monotone" dataKey="count" stroke="#6d63d9" strokeWidth={3} fill="#6d63d922"/></AreaChart></ResponsiveContainer></div></section><section className="card section"><div className="section-title"><h2>My next steps</h2><button className="btn" onClick={()=>go("commitments")}>View all <ChevronRight size={15}/></button></div>{pending.slice(0,4).map(c=><div className="commitment-mini" key={c.id}><div className="check-ring"/><div style={{flex:1}}><b>{c.title}</b><div className="muted">{mistake(c.mistakeId).name}</div></div></div>)}</section></div></>}
function Patterns({items,records,open,home,create}:{items:Mistake[];records:RecordItem[];open:(m:Mistake)=>void;home:()=>void;create:()=>void}){return <><div className="page-actions"><button className="btn btn-soft" onClick={home}>Back to home</button><button className="btn btn-primary" onClick={create}><Plus size={16}/> Create custom pattern</button></div><div className="soft-banner"><Heart size={19}/><span>These are not labels for who you are. They are behaviors you can understand and change.</span></div><div className="mistake-grid">{items.map(m=><button className="mistake" key={m.id} onClick={()=>open(m)}><div className="mistake-top"><div className="mistake-icon" style={{background:m.color+"20",color:m.color}}><Brain size={19}/></div><span className="badge" style={{background:m.color+"18",color:m.color}}>{records.filter(r=>r.mistakeId===m.id).length+m.count} observations</span></div><h3>{m.name}</h3><div className="muted">{m.category} · Trigger: {m.trigger}</div><div className="intention">Next time: {m.intention}</div></button>)}</div></>}
function Commitments({items,mistake,complete}:{items:Commitment[];mistake:(id:number)=>Mistake;complete:(id:number)=>void}){return <section className="card section"><div className="section-title"><div><h2>Small, practical commitments</h2><div className="muted">These are for returning to your path, never punishment.</div></div></div>{items.map(c=><div className="commitment-row" key={c.id}><div className="icon-box"><Target/></div><div style={{flex:1}}><b>{c.title}</b><div className="muted">{c.reason} · {mistake(c.mistakeId).name}</div></div><span className={`badge ${deadlineState(new Date(c.due))==="overdue"?"orange":"blue"}`}>{new Date(c.due).toLocaleDateString()}</span><button className="btn btn-soft" onClick={()=>complete(c.id)}><CheckCircle2 size={15}/> I did it</button></div>)}</section>}
function Journal({records,commitments,mistake}:{records:RecordItem[];commitments:Commitment[];mistake:(id:number)=>Mistake}){return <div className="grid-2"><section className="card section"><div className="section-title"><h2>Awareness notes</h2></div>{records.map(r=><div className="journal-entry" key={r.id} style={{borderRight:0,borderLeft:`3px solid ${mistake(r.mistakeId).color}`}}><b>{mistake(r.mistakeId).name}</b><div className="muted">{r.date} · Feeling: {r.feeling}</div><p>{r.note}</p><div className="lesson"><Sparkles size={14}/> Learning: {r.lesson||mistake(r.mistakeId).intention}</div></div>)}</section><section className="card section"><h2>My small wins</h2>{commitments.filter(c=>c.status==="done").map(c=><div className="commitment-mini" key={c.id}><CheckCircle2 color="#168259"/><b>{c.title}</b></div>)}</section></div>}
function Insights({records,patterns}:{records:RecordItem[];patterns:Mistake[]}){const data=patterns.map(m=>({name:m.name,count:records.filter(r=>r.mistakeId===m.id).length+m.count})).sort((a,b)=>b.count-a.count);return <section className="card section"><div className="section-title"><h2>Patterns I notice most</h2><span className="badge purple">Last 30 days</span></div>{data.map(d=><div className="insight-bar" key={d.name}><span>{d.name}</span><div><i style={{width:`${Math.min(100,d.count/12*100)}%`}}/></div><b>{d.count}</b></div>)}</section>}
function HistoryView({records,mistake}:{records:RecordItem[];mistake:(id:number)=>Mistake}){return <section className="card section"><div className="section-title"><div><h2>Complete history</h2><div className="muted">Nothing is removed unless you choose to remove it.</div></div></div>{records.map(r=><div className="timeline-item" key={r.id} style={{borderRight:0,borderLeft:"1px solid var(--line)",paddingLeft:26}}><div className="timeline-dot" style={{background:mistake(r.mistakeId).color,left:-6,right:"auto"}}/><div><b>{mistake(r.mistakeId).name}</b><div className="muted">{r.date}</div><p>{r.note}</p></div></div>)}</section>}
function SettingsView(){return <div className="grid-2"><section className="card section"><h2>Reminders</h2><label className="setting-label">Daily review time<input className="field" type="time" defaultValue="21:00"/></label><label className="setting-label">Message style<select className="field"><option>Kind and encouraging</option><option>Short and direct</option><option>No notifications</option></select></label><button className="btn btn-primary">Save</button></section><section className="card section"><h2>Privacy</h2><p className="muted">This is your private space. Export a copy of your notes at any time.</p><button className="btn btn-soft"><Archive size={16}/> Download backup</button></section></div>}
